"""init

Revision ID: 0b7f99b782b6
Revises:
Create Date: 2024-10-20 18:43:13.127123

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "0b7f99b782b6"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
