"""init

Revision ID: 4475672645e4
Revises: 
Create Date: 2024-10-19 15:53:41.877236

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4475672645e4'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_author_book', 'author', ['author_id'], ['id'])
        batch_op.create_foreign_key('fk_publisher_book', 'publisher', ['publisher_id'], ['id'])
        batch_op.create_foreign_key('fk_genre_book', 'genre', ['genre_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_constraint('fk_author_book', type_='foreignkey')
        batch_op.drop_constraint("fk_publisher_book", type_='foreignkey')
        batch_op.drop_constraint("fk_genre_book", type_='foreignkey')

    # ### end Alembic commands ###
