"""update_library_models

Revision ID: 5239b2b254d7
Revises: 4475672645e4
Create Date: 2024-10-20 15:47:22.838801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision: str = '5239b2b254d7'
down_revision: Union[str, None] = '4475672645e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth_date', sa.Date(), nullable=False))

    with op.batch_alter_table('publisher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('est_date', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publisher', schema=None) as batch_op:
        batch_op.drop_column('est_date')

    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.drop_column('birth_date')

    # ### end Alembic commands ###
