"""create_borrowing_model

Revision ID: af64bff0ab78
Revises: 5239b2b254d7
Create Date: 2024-10-20 16:44:22.491397

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'af64bff0ab78'
down_revision: str | None = '5239b2b254d7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_book')
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('in_stock', sa.Boolean(), nullable=False, default=True))
        batch_op.alter_column('genre_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('publisher_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('author_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('bookborrow', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_borrowed', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('date_to_return', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('date_returned', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookborrow', schema=None) as batch_op:
        batch_op.drop_column('date_returned')
        batch_op.drop_column('date_to_return')
        batch_op.drop_column('date_borrowed')

    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('author_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('publisher_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('genre_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('in_stock')

    op.create_table('_alembic_tmp_book',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('ISBN', sa.VARCHAR(), nullable=False),
    sa.Column('publish_date', sa.DATE(), nullable=False),
    sa.Column('genre_id', sa.INTEGER(), nullable=False),
    sa.Column('publisher_id', sa.INTEGER(), nullable=False),
    sa.Column('author_id', sa.INTEGER(), nullable=False),
    sa.Column('in_stock', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], name='fk_author_book'),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], name='fk_genre_book'),
    sa.ForeignKeyConstraint(['publisher_id'], ['publisher.id'], name='fk_publisher_book'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
