name: workflow.yml
on:
  pull_request:
    branches:
      - master
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    strategy:
      matrix:
        python-version: [3.12]

    steps:
      - uses: actions/checkout@v4
      - name: Set Up Python
        uses:  actions/setup-python@v5
        with:
          python-version: ${{matrix.python-version}}

      - name: Install Dependencies
        run: pip install pipenv | pipenv install -d

      - name: Run App Tests
        run: pytest -v | pytest --cov=app --cov-fail-under=90
